name: Custom Action Workflow

on: [push]

jobs:
  custom-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run custom action
        uses: ClubCedille/Cedille-Actions-By-Example/actions@master
        with:
          message: "Bonjour depuis l'action personnalisée !"
